name = "ToeplitzCUDA_Eigen_Refinement"
uuid = "3d553849-0536-4eb2-b845-3191e399a7ed"
authors = ["David Meadon"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
